locals {
  geocode_lookup_list = [
    { short_name : "northeurope", full_name : "North Europe", geo_code : "ne" },
    { short_name : "westeurope", full_name : "West Europe", geo_code : "we" },
    { short_name : "francecentral", full_name : "France Central", geo_code : "frc" },
    { short_name : "francesouth", full_name : "France South", geo_code : "frs" },
    { short_name : "germanynorth", full_name : "Germany North", geo_code : "gn" },
    { short_name : "germanywestcentral", full_name : "Germany West Central", geo_code : "gwc" },
    { short_name : "italynorth", full_name : "Italy North", geo_code : "itn" },
    { short_name : "norwayeast", full_name : "Norway East", geo_code : "nwe" },
    { short_name : "norwaywest", full_name : "Norway West", geo_code : "nww" },
    { short_name : "polandcentral", full_name : "Poland Central", geo_code : "plc" },
    { short_name : "swedencentral", full_name : "Sweden Central", geo_code : "sdc" },
    { short_name : "swedensouth", full_name : "Sweden South", geo_code : "sds" },
  ]

  location_lookup = merge(
    { for location in local.geocode_lookup_list : lower(location.short_name) => location },
    { for location in local.geocode_lookup_list : lower(location.full_name) => location }
  )

  location_private_dns_zones = flatten([for location in var.locations : [
    "privatelink.${local.location_lookup[location].short_name}.kusto.windows.net",
    "privatelink.${local.location_lookup[location].short_name}.azmk8s.io",
    "privatelink.${local.location_lookup[location].geo_code}.backup.windowsazure.com",
    "privatelink.${local.location_lookup[location].short_name}.azurecontainerapps.io",
    "${local.location_lookup[location].short_name}.data.privatelink.azurecr.io",
    "privatelink.${local.location_lookup[location].short_name}.prometheus.monitor.azure.com"
  ]])
  
  partitioned_private_dns_zones = [ for i in range(var.partition_count + 1) : format("privatelink.%s.azurestaticapps.net",i) ]

  private_dns_zones = {
    for dns_zone in distinct(concat(var.additional_zones, local.location_private_dns_zones, local.partitioned_private_dns_zones,
      [
        "privatelink.api.azureml.ms",
        "privatelink.notebooks.azure.net",
        "privatelink.cognitiveservices.azure.com",
        "privatelink.openai.azure.com",
        "privatelink.services.ai.azure.com",
        "privatelink.directline.botframework.com",
        "privatelink.token.botframework.com",
        "privatelink.sql.azuresynapse.net",
        "privatelink.dev.azuresynapse.net",
        "privatelink.azuresynapse.net",
        "privatelink.servicebus.windows.net",
        "privatelink.datafactory.azure.net",
        "privatelink.adf.azure.com",
        "privatelink.azurehdinsight.net",
        "privatelink.blob.core.windows.net",
        "privatelink.queue.core.windows.net",
        "privatelink.table.core.windows.net",
        "privatelink.analysis.windows.net",
        "privatelink.pbidedicated.windows.net",
        "privatelink.prod.powerquery.microsoft.com",
        "privatelink.azuredatabricks.net",
        "privatelink.fabric.microsoft.com",
        "privatelink.batch.azure.com",
        "privatelink-global.wvd.microsoft.com",
        "privatelink.wvd.microsoft.com",
        "privatelink.azurecr.io",
        "privatelink.database.windows.net",
        "privatelink.documents.azure.com",
        "privatelink.mongo.cosmos.azure.com",
        "privatelink.cassandra.cosmos.azure.com",
        "privatelink.gremlin.cosmos.azure.com",
        "privatelink.table.cosmos.azure.com",
        "privatelink.analytics.cosmos.azure.com",
        "privatelink.postgres.cosmos.azure.com",
        "privatelink.mongocluster.cosmos.azure.com",
        "privatelink.postgres.database.azure.com",
        "privatelink.mysql.database.azure.com",
        "privatelink.mariadb.database.azure.com",
        "privatelink.redis.cache.windows.net",
        "privatelink.redisenterprise.cache.azure.net",
        "privatelink.redis.azure.net",
        "privatelink.his.arc.azure.com",
        "privatelink.guestconfiguration.azure.com",
        "privatelink.dp.kubernetesconfiguration.azure.com",
        "privatelink.eventgrid.azure.net",
        "privatelink.ts.eventgrid.azure.net",
        "privatelink.azure-api.net",
        "privatelink.azurehealthcareapis.com",
        "privatelink.dicom.azurehealthcareapis.com",
        "privatelink.azure-devices.net",
        "privatelink.azure-devices-provisioning.net",
        "privatelink.api.adu.microsoft.com",
        "privatelink.azureiotcentral.com",
        "privatelink.digitaltwins.azure.net",
        "privatelink.media.azure.net",
        "privatelink.api.videoindexer.ai",
        "privatelink.azure-automation.net",
        "privatelink.siterecovery.windowsazure.com",
        "privatelink.oms.opinsights.azure.com",
        "privatelink.ods.opinsights.azure.com",
        "privatelink.agentsvc.azure-automation.net",
        "privatelink.purview.azure.com",
        "privatelink.purviewstudio.azure.com",
        "privatelink.purview-service.microsoft.com",
        "privatelink.prod.migration.windowsazure.com",
        "privatelink.grafana.azure.com",
        "privatelink.vaultcore.azure.net",
        "privatelink.managedhsm.azure.net",
        "privatelink.azconfig.io",
        "privatelink.attest.azure.net",
        "privatelink.file.core.windows.net",
        "privatelink.web.core.windows.net",
        "privatelink.dfs.core.windows.net",
        "privatelink.afs.azure.net",
        "privatelink.search.windows.net",
        "privatelink.azurewebsites.net",
        "scm.privatelink.azurewebsites.net",
        "privatelink.service.signalr.net",
        "privatelink.azurestaticapps.net",
        "privatelink.account.maps.azure.com",
        "privatelink.webpubsub.azure.com",
      ])) : dns_zone => {
      resolution_policy = lookup(var.zone_resolution_policies, dns_zone, "Default")
    }
  }
}
